### ISSUE TITLE
Remove the `latest` symlink from dcos-docs

### ISSUE THREAD

**Issue by karlkfi** [dcos/dcos-website#218]
The symlink is causing confusion. I think it would be clearer if dcos-website just keeps track of the latest docs version.

**Comment by kevinkalle** [comment]
@karlkfi something we can do here?

**Comment by karlkfi** [comment]
@kevinkalle If you want to. The goal was just to get the symlink out of the dcos-docs repo, because it's an artifact of the website, not the source docs, and occasionally people have done `git add latest/<file>` which causes problems. I kind of figure the website is owned by engineers, but non-engineers should be able to contribute to the docs.

**Comment by karlkfi** [comment]
After talking to @pyronicide it sounds like the symlink is vestigial. S3 is handling the redirect from `latest` -> `1.7`. So as long as it doesn't break the local preview, the symlink can be deleted.

**Comment by karlkfi** [comment]
Confirmed. The dev server does a rewrite. It acts different than the S3 redirect, but it's close enough.

**Comment by karlkfi** [comment]
Removed: https://github.com/dcos/dcos-docs/commit/8bbe2fd96bb8595736bd2d0deb94aa45cca00b42
