### ISSUE TITLE
Release notes: remove duplicate item, correct Marathon release notes link

### ISSUE THREAD

**Issue by jgehrcke** [dcos/dcos-website#574]
About https://dcos.io/releases/1.7.0/:

* The point "Distributed DNS Server to enable highly available DNS deployment for service discovery and service availability" is listed under two sections, "Improved DC/OS installation" as well as "DC/OS Networking". It must be removed from "Improved DC/OS installation".

* The link to Marathon release notes needs to be updated.
It's currently https://github.com/mesosphere/marathon/releases/edit/v1.0.0-RC1, note the `edit.` It should probably be https://github.com/mesosphere/marathon/releases. @aquamatthias please confirm.

**Comment by joel-hamill** [comment]
Fix is awaiting merge: https://github.com/dcos/dcos-website/pull/668

**Comment by karlkfi** [comment]
the marathon link is merged. was there another one for the duplicate item, @joel-hamill ?

**Comment by joel-hamill** [comment]
@karlkfi @jgehrcke I don't see any duplicate bullet for Distributed DNS. https://dcos.io/releases/1.7.0/

**Comment by jgehrcke** [comment]
@joel-hamill the duplicate item has been covered by beautiful @adam-mesos in https://github.com/dcos/dcos-website/pull/665 :)

**Comment by karlkfi** [comment]
Great. Closing this out then
