### ISSUE TITLE
The logos on the quotes page are not the same size

### ISSUE THREAD

**Issue by williamsaaron** [dcos/dcos-website#638]
Especially Samsung and Vamp, which are next to eachother, and Samsung looks much smaller than Vamp. And Redapt above it also looks small.

Maybe they're all the same height, but they look different.

This isn't urgent.

**Comment by TimonVS** [comment]
Yeah this is kind of hard. Because as you say, they all have the same height right now. We'd have to tweak the logos on an individual basis. What are your thoughts @Martijn-Vermeulen?

**Comment by ashenden** [comment]
Let's not spend a ton of energy on this.  If we can make small CSS tweaks, great.

**Comment by kevinkalle** [comment]
We spend some time on this but it doesn't improve the entire logo section. Suggest to leave as is, before you know it we are tweaking every logo that is on there.
