### ISSUE TITLE
Get started flow confuses user

### ISSUE THREAD

**Issue by mhausenblas** [dcos/dcos-website#671]
When visiting https://dcos.io/get-started/ users get the impression that they are downloading and installing a specifically tailored version of DC/OS, for example, if they select Kafka, then only Kafka is usable and the other services not.

**Comment by kevinkalle** [comment]
@ashenden what's your take on this? cc: @williamsaaron any thoughts..?

**Comment by kevinkalle** [comment]
@ashenden can you share your thoughts on this, I'm not sure if we know exactly how to improve this.

**Comment by ashenden** [comment]
This is probably something we could solve with language.  For example, on the Step 1, we could add friendly copy to imply you can come back to get instructions on installing other services as well linking into the docs.  Similarly, on Step 3, we could communicate a way to choose a different service, leaving Step 2 in a "Selected" state.

**Comment by kevinkalle** [comment]
Agreed. @williamsaaron do you want to provide the copy for this?

**Comment by ashenden** [comment]
@kevinkalle I suggest that you guys look at the problem and see if you can make a solution work.  We can then work to build copy to support it if it makes sense.  I think a simple headline and maybe a clear CTA on Step 3 to choose a different service from Step 1 would be enough.

**Comment by kevinkalle** [comment]
@mhausenblas we don't know what to improve also since I think the only change could be copy related. Please let us know if there is anything else you see as a possible improvement.
