### ISSUE TITLE
Releases page should link to AWS templates

### ISSUE THREAD

**Issue by cmaloney** [dcos/dcos-website#675]
The EarlyAccess box should link to: https://downloads.dcos.io/dcos/EarlyAccess/aws.html as well as the dcos_generate_config.sh it currently does

**Comment by karlkfi** [comment]
Should it link to Azure marketplace too?

**Comment by cmaloney** [comment]
Probably, although that doesn't get updated continuously / as we promote new builds to EarlyAccess

**Comment by kevinkalle** [comment]
@cmaloney something we can do here? cc: @TimonVS

**Comment by karlkfi** [comment]
I think this probably needs to be designed first. 

@ashenden: Got any ideas about how to show the AWS templates? 

I'm not very excited about linking to that very engineering-y AWS templates page from the release page without going through the cloud install steps, but maybe you have an idea about how to do it?

/cc @pyronicide @mhausenblas

**Comment by ashenden** [comment]
Good call @karlkfi.  We should mirror the behavior we use to have on the mesosphere.com site.  It looked like this (http://cl.ly/363x0l273h2b).

Where do we link to this page currently?

**Comment by karlkfi** [comment]
The only link to it is https://dcos.io/docs/1.7/administration/installing/cloud/aws/ (Step 2) AFAIK.
If we add a new way to get to the templates we'll need to update the install docs too.

**Comment by ashenden** [comment]
Which install docs are you referencing?  Link?

Given this link lives in the docs, triggering a pop-up modal like the one in the video above is pretty unlikely.  We could, however, place a nicer version of this (https://downloads.dcos.io/dcos/EarlyAccess/aws.html) directly in the documentation.  How would this be maintained?

**Comment by karlkfi** [comment]
I linked to the install doc. 

If you want something like the video you made it would have to be a part of dcos-website, and then the docs would just walk you through using it.

That list page is generated by the dcos release builder. If you want it nicer you'll have to update the release builder itself.

**Comment by cmaloney** [comment]
@ashenden the page source is: https://github.com/dcos/dcos/blob/master/gen/aws/templates/aws.html

**Comment by ashenden** [comment]
@kevinkalle @TimonVS @davidvanleeuwen any ideas on how we could pull this off in a clean way?  Basically we have 3 options...
1) Update this page styling -- https://downloads.dcos.io/dcos/EarlyAccess/aws.html
2) Update the doc page referencing thing link in #1 (https://dcos.io/docs/1.7/administration/installing/cloud/aws/) to include all the content from the link in #1 in a nice styled table.
3) Create some sexy page/modal on dcos.io that functions like this (http://cl.ly/363x0l273h2b) and can be invoked from any docs link or direct/dedicated URL.

**Comment by TimonVS** [comment]
@ashenden I really like option 3. But I'm not really sure if it adds any value as opposed to option 2. Since we're putting it in the docs I think option 2 makes more sense.
But I'm interested to hear other opinions :).

**Comment by karlkfi** [comment]
The docs are rather verbose. I like the idea of a curated, "good UX" option 3, with verbose walkthrough docs that show how to use it for people that want their hand held.

**Comment by pyronicide** [comment]
I like option 3 as long as we can update it automatically. Maybe have it read from some JSON hosted on `downloads.dcos.io`?

**Comment by TimonVS** [comment]
I do like option 3. But I don't like having it in the docs to be honest. We could make a separate page for it if that makes sense?

**Comment by ashenden** [comment]
Yeah, a separate page or a modal that lives globally on dcos.io and can be invoked from any page would be ideally.  What's most important is that we can link into the modal (and/or) page from anywhere.

**Comment by TimonVS** [comment]
@ashenden to get this straight, right now it's only for AWS, but in the future this may also include Azure, right? In that case I'd prefer a page because that's a lot of info for a modal. 
In general I'd prefer a page because that'd make linking to it easier (linking to a modal is kind of a no-go for me).

**Comment by ashenden** [comment]
Makes sense.  If we have azure, this would a different page with likely a different flow.  But for now AWS is the only platform we need templates for.  Can you guys work on putting this together?  I'd like to pull heavily from this direction (http://cl.ly/363x0l273h2b).  Rather than big messy table like this (https://downloads.dcos.io/dcos/EarlyAccess/aws.html), we have something a little more UX friendly.

**Comment by TimonVS** [comment]
Yes, I'll discuss with Martijn about the design today :).

**Comment by Martijn-Vermeulen** [comment]
Design: 
![aws](https://cloud.githubusercontent.com/assets/10687330/14882286/2a16b6a4-0d38-11e6-966f-a83cec6dc43b.jpg)

When we add other services like Azure for example, we can add an segmented control on top of this page to switch between the different services. This allows us to have different flows for services without having a separate page for every service.

**Comment by ashenden** [comment]
Sounds good.  Seems strange though to have this all in a box in the middle of the page.  What I'd rather us have is move the "DC/OS EA AWS CloudFormation" as the title of the page -- likely worded better.  The description could sit in the header or on page, and then page itself is tailored with the correct content.

If we have other platforms in the future, the pages and the instructions will probably be pretty different, so recycling this page probably won't happen.  Let's optimize just for AWS right now.

**Comment by karlkfi** [comment]
Would like it all to be above the fold on a laptop screen if possible.

**Comment by cmaloney** [comment]
Is that for the `aws.html` page or `dcos.io` page? If it's for `aws.html` I want to note that the page needs to be fully self contained and published by the release tools.

For the "release" page the bigger question is how does that look like as the extra buttons inside hte boxes on: https://dcos.io/releases/

**Comment by ashenden** [comment]
@cmaloney we are suggesting a standalone page on dcos.io to replace this endpoint - https://downloads.dcos.io/dcos/EarlyAccess/aws.html.

**Comment by cmaloney** [comment]
That endpoint is going to continue existing (It is really, really useful from an engineering side).

To make a separate page on dcos.io we probably need to publish as part of the release some JSON data of where all the buttons should point? (If so this isn't going to be doable before 1.8)

**Comment by ashenden** [comment]
Proposal...
* Redirect that URL to something like dcos.io/install/aws
* You and or someone else manually updates those links on dcos.io
* (future) We work with Awkward (dev partners) to propose a simple JSON format you can expose to dcos.io to dynamically populate so you no longer have to manually do it.

Keep in mind, up until recently, these button links were hard-coded and manually maintained on mesosphere.com/amazon/setup

**Comment by cmaloney** [comment]
We create that page / set of buttons for every PR to dcos/image, they link to very specific artifacts which are critical for being able to develop / work on the AWS templates. It's not redirecting or going away. Most of the pages we build of that are not "published" releases.

I strongly believe that manually updating the page will result in things being forgotten or messed up. Currently the release process generates that page with the release, and has a strong guarantee everything inside of it is correct / matching up. Hand building all the links is very likely to go wrong.

for the individual channels there are the "Well known" urls which can be used which is what the mesosphere.com "Install AWS" page linked to. Those are the sort of button that really should just live in the release page. People who are looking to get the new CF template need the buttons / templates directly, not a tutorial.

**Comment by ashenden** [comment]
Ok.  Work with me on this.  What I want is a better looking version of that page.  Creating it as a standalone page, requires standalone styles, and then that also becomes difficult to maintain.

Since you already generate that page dynamically, could you not generate a JSON blob manually that we tap into and render the content as desired on dcos.io?

Looking for solutions here that do not require us to build markup styling directly on https://downloads.dcos.io/dcos/EarlyAccess/aws.html

**Comment by cmaloney** [comment]
I agree on the better looking version. Just trying to note that there are elements of that page which are very engineering internal. Making it pretty but loosing critical functionality isn't a good idea.

Yes, we can definitely generate a JSON blob, that would land sometime in 1.8 which was my point with it earlier. It's not going to happen for 1.7-Open EA or GA (So the EarlyAccess and "stable" channels for this release cycle won't have it). It would be in the "master" branch sooner / whenever we land the code to make it.

**Comment by ashenden** [comment]
Ok.  Let's have Awkward build out the page with a sample JSON blob.  We won't publish it, but can use it as an example of how it would look and how we'd need the JSON to be formatted.

Ultimately, I would hope to replace the page with this new page.  So, if we can work together to make that the goal, that would be ideal.

**Comment by cmaloney** [comment]
Eng wise every single time someone makes a PR to https://github.com/dcos/dcos that PR gets built and gets one of those aws.html pages which is critical to being able to test that PR inside of AWS. Those PRs shouldn't show up on dcos.io/releases (or separate / new pages inside of there). There is also some benefit to those not looking like "professional" / whole releases, since it is arbitrary development code submitted by third parties which hasn't necessarily been reviewed yet.

**Comment by ashenden** [comment]
Thats fine, as long as the links for the version referenced in the docs is styled nice and references something stable.

**Comment by Martijn-Vermeulen** [comment]
@TimonVS: Do you need anything from me for this issue?

**Comment by TimonVS** [comment]
@ashenden Styling is ready. Could you provide me with the JSON blob?

**Comment by karlkfi** [comment]
@cmaloney: you wanna sketch out what the build.json metadata is gonna look like? We could just hardcode one for EA until it's auto-generated.

**Comment by kevinkalle** [comment]
@cmaloney can you provide us with a time estimate so we can plan this one accordingly? Want to get most of this done this week.

**Comment by kevinkalle** [comment]
https://github.com/dcos/dcos-website/issues/705
