### ISSUE TITLE
Switch @dcos_io to @dcos

### ISSUE THREAD

**Issue by williamsaaron** [dcos/dcos-website#679]
We got @dcos from Twitter. Awesome.

So, we need to get all our links / content switched over to reference @dcos. We don't want to deploy it yet, we have to work out the timing with Twitter to make sure they have us switched first, but I'll work out the timing if someone else will get all of the pages updated, across the site, and ready to go, so we can merge at a moment's notice ..

Who wants this one? @ashenden or @pyronicide or @mhausenblas? First one to grab it gets it. :)

**Comment by ashenden** [comment]
I got it

**Comment by ashenden** [comment]
Changes made in this branch -- https://github.com/dcos/dcos-website/tree/feature/twitter-dcos

When we're ready I'll merge it in.

**Comment by williamsaaron** [comment]
Thanks, @ashenden! I'll update this issue when I have a time.

**Comment by mhausenblas** [comment]
@williamsaaron does that mean same credentials and account or new credentials and new account that is, I will to do the styling and profile setup again? If new account pls share credentials via OneLogin?

**Comment by mhausenblas** [comment]
BTW, that's awesome :)

**Comment by williamsaaron** [comment]
Not sure yet. I think they will do the switch of styling, etc. for us - just move everything including the followers from dcos_io to dcos, but I have to confirm.

We have the credentials for the account now, so the transition should happen today ..

**Comment by kevinkalle** [comment]
@williamsaaron something we can do here? cc: @TimonVS

**Comment by ashenden** [comment]
@williamsaaron, @kevinkalle, and @TimonVS I have a fix for this in the branch `feature/twitter-dcos`.  As soon as you say the word @williamsaaron we can merge this up live.

**Comment by williamsaaron** [comment]
I will let you know as soon as the transfer is done. I'm talking to them daily ..

**Comment by kevinkalle** [comment]
Planning this for next week @williamsaaron let us know when to make the change.
