### ISSUE TITLE
Add Star button on dcos.io for easy "starring"

### ISSUE THREAD

**Issue by AmrAbdelrazik** [dcos/dcos-website#683]
Let's add a button on the dcos.io website so that people can easily star the project

Check https://buttons.github.io/

**Comment by TimonVS** [comment]
I'm not exactly sure where to put the button. @Martijn-Vermeulen maybe you can give me a hint? :)

**Comment by TimonVS** [comment]
@ashenden do we really want this? We already have a link to GitHub in the header. Other popular projects like Angular and React also don't have a star button on their website.
We can't really find a nice place to put the button.

**Comment by ashenden** [comment]
This is something we have had requested. I'm sure can find a way to make
this work. Consider a placement nearby the CTAs. If also check out other
popular open source projects for inspiration. Many of them have a button of
some nature to "star" on Github.

—
*John Ashenden*

**Comment by Martijn-Vermeulen** [comment]
Adding it nearby the CTA's in the header feels a bit cluttered. 

There're a few other things we can do: 

1. We can add an dropdown to the GitHub link in the menu, with an option to go to the GitHub repo, the option to star and maybe add an option to go the the latest update or something. 

2. We can add the star button to the footer.

**Comment by ashenden** [comment]
Example of use in the wild -- http://jenkins-contrib-themes.github.io/jenkins-material-theme/

Definitely don't want to to hide it under a dropdown.  Footer could work, but likely won't be clicked.  Let's at least put together some quick mockups for reference rather than kicking it back and forth over text.

**Comment by Martijn-Vermeulen** [comment]
@ashenden Created some mockups for the homepage with the Star Button:

1.
![1](https://cloud.githubusercontent.com/assets/10687330/14963209/e0e82fb2-10a2-11e6-84eb-987ee7e88662.jpg)

2. 
![2](https://cloud.githubusercontent.com/assets/10687330/14963215/e462eb32-10a2-11e6-86f0-8d0db4d07a44.jpg)

3. 
![3](https://cloud.githubusercontent.com/assets/10687330/14963219/e8aca174-10a2-11e6-98d5-f905ec822a16.jpg)

4. 
![4](https://cloud.githubusercontent.com/assets/10687330/14963221/ecc1ecd8-10a2-11e6-8893-a6bf9130d245.jpg)

5. 
![5](https://cloud.githubusercontent.com/assets/10687330/14963224/f1d47fec-10a2-11e6-8091-f7f90fcd5eb1.jpg)

6. 
![6](https://cloud.githubusercontent.com/assets/10687330/14963227/f69e5552-10a2-11e6-887f-4ec15d6d7fe4.jpg)

7. 
![7](https://cloud.githubusercontent.com/assets/10687330/14963233/fd4ff87e-10a2-11e6-840e-10b5ed860e85.jpg)

Please let us know which option you prefer.

**Comment by ashenden** [comment]
@Martijn-Vermeulen have you tried out a version with the smaller star button?  Might also look good in the header next to the github link.

**Comment by Martijn-Vermeulen** [comment]
@ashenden 
![homepage copy 5](https://cloud.githubusercontent.com/assets/10687330/14966887/e41253cc-10b4-11e6-9b3e-5ab6724ca1f2.jpg)

**Comment by ashenden** [comment]
I like this more.  What do you think?

**Comment by Martijn-Vermeulen** [comment]
From all possibilities I also like this one the most.

**Comment by ashenden** [comment]
@williamsaaron what do you think?

**Comment by TimonVS** [comment]
@ashenden Can't we just replace the GitHub menu item with the GitHub star button in that case? The menu item redirects to the DCOS GitHub organization which doesn't really make sense to me.

**Comment by ashenden** [comment]
I would be ok with that. Let's do it .

—
*John Ashenden*
