### ISSUE TITLE
Update search functionality styling

### ISSUE THREAD

**Issue by ashenden** [dcos/dcos-website#684]
@pyronicide can you elaborate here on what is now available to us?

**Comment by pyronicide** [comment]
See https://www.algolia.com/doc/search/auto-complete. It is already enabled, just display the search field.

**Comment by williamsaaron** [comment]
@kevinkalle @ashenden anything keeping us from turning this on?

**Comment by ashenden** [comment]
Nothing from my end.  @kevinkalle @davidvanleeuwen can we get this hooked up asap this week?
