### ISSUE TITLE
Implement Algolia search

### ISSUE THREAD

**Issue by davidvanleeuwen** [dcos/dcos-website#695]
Right now `.docs-search` is on `display: none`. It needs to be enabled again once Algolia has been implemented with the design. See `.docs-layout__docs-results` and this code: https://github.com/dcos/dcos-website/commit/a8dbf8d009e0e1eb3483274579595e39a4de4088 for markup things.

![pasted_image_at_2016_04_29_12_59_pm](https://cloud.githubusercontent.com/assets/238946/14914463/99b33a28-0e0a-11e6-9151-8a6ac1689891.png)I

**Comment by ashenden** [comment]
Can we please style this too?  Badass that it's working, but it looks like @pyronicide designed it.

cc/ @kevinkalle

**Comment by davidvanleeuwen** [comment]
HTML/CSS is already there 👍 We already had the search using lunr, but removed it as it didn't work with so many `.md` files.

**Comment by ashenden** [comment]
K. I'm looking for the Algolia dropdown box itself to not look like shit.

**Comment by TimonVS** [comment]
Updated styling in #702.
![https://i.imgur.com/7V6l5TB.png](https://i.imgur.com/7V6l5TB.png)

Is this to your liking @ashenden?

**Comment by ashenden** [comment]
Looks good to me.
