### ISSUE TITLE
Create build.json for release page

### ISSUE THREAD

**Issue by kevinkalle** [dcos/dcos-website#705]
@cmaloney: you wanna sketch out what the build.json metadata is gonna look like? We could just hardcode one for EA until it's auto-generated.

**Comment by kevinkalle** [comment]
@ashenden we can't finalise this page without this, can you let us know when we could get this part?

**Comment by ashenden** [comment]
Understood.  Let's leave this in limbo for now.  Once @cmaloney is ready to support us on this, we can pick it back up again.

@cmaloney if you happen to have a rough idea of how you'd formate the JSON, we can at least hook this up with dummy data.

**Comment by karlkfi** [comment]
Ticket just got bumped out of the 1.8.0 release backlog: https://dcosjira.atlassian.net/browse/DCOS-86
