### ISSUE TITLE
Algolia logo

### ISSUE THREAD

**Issue by pyronicide** [dcos/dcos-website#707]
We're using Algolia for site search and one of the requirements is to show their logo. Can we get it added to the site?

**Comment by ashenden** [comment]
Do they have any guidelines for how it must be used?

**Comment by pyronicide** [comment]
Apparently, we removed it from the CSS and just need to add it back in. I assume that means the search box.

**Comment by ashenden** [comment]
@pyronicide We did.  I'm asking if the dropdown is the only acceptable place to put their logo?  Do they require it be in the dropdown or could we move it somewhere closer to the footer of the posts?

**Comment by pyronicide** [comment]
@ashenden you mean the bottom of the page?

**Comment by ashenden** [comment]
Yes.  I'm just looking to know how strict they are about where attribution is giving.

**Comment by TimonVS** [comment]
Ah yeah, I hid the logo. I can change it back if that's needed :).

**Comment by pyronicide** [comment]
@TimonVS sounds like it needs to be in the search dialog. Thanks!

**Comment by TimonVS** [comment]
I'll fix this tomorrow!






On Fri, May 13, 2016 at 7:12 AM -0700, "Thomas Rampelberg" <notifications@github.com> wrote:





@TimonVS sounds like it needs to be in the search dialog. Thanks!

---
